name: simple-JSON-parser
version: 0.1.0.0
github: "githubuser/simple-JSON-parser"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/githubuser/simple-JSON-parser#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 2.0 && < 3.0
  - bytestring >= 0.10 && < 1.0
  - text >= 1.2 && < 3.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  simple-JSON-parser-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - simple-JSON-parser

tests:
  simple-JSON-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - simple-JSON-parser
      - hspec >= 2.0
